apiVersion: v1
kind: Pod
metadata:
  name: controller
  labels:
    name: controller
  namespace: ma-schuetz-dcun
spec:
  containers:
    - name: controller
      image: sl3nx/dcun:controller
      resources:
        limits:
          memory: "256Mi"
          cpu: "500m"
      ports:
        - containerPort: 50000
      imagePullPolicy: Always
  restartPolicy: Never
