apiVersion: v1
kind: Pod
metadata:
  name: logstorage
  # namespace: ma-schuetz-dcun
  labels:
    name: logstorage

spec:
  containers:
    - name: logstorage
      image: logstorage
      imagePullPolicy: Never
      ports:
        - containerPort: 50000
      resources:
        limits:
          memory: "20Gi"
          cpu: "2"

---
apiVersion: v1
kind: Service
metadata:
  name: logstorage
  namespace: ma-schuetz-dcun
  labels:
    name: logstorage
spec:
  ports:
    - port: 50000
  type: ClusterIP
  selector:
    name: logstorage
