apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: node
  # namespace: ma-schuetz-dcun
spec:
  selector:
    matchLabels:
      name: node
  serviceName: stsservice
  replicas: 50 # Num of nodes

  template:
    metadata:
      labels:
        name: node
    spec:
      containers:
        - name: node
          image: mynode
          imagePullPolicy: Never
          # imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 50000

---
apiVersion: v1
kind: Service
metadata:
  name: stsservice
  namespace: ma-schuetz-dcun
  labels:
    name: node
spec:
  ports:
    - port: 50000
  type: ClusterIP
  selector:
    name: node
---

