apiVersion: v1
kind: Pod
metadata:
  name: testclient
  labels:
    name: testclient
spec:
  containers:
    - name: testclient
      image: myclient
      imagePullPolicy: Never
      ports:
        - containerPort: 50000
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
